/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;
import edu.au.cc.gallery.tools.UserAdmin;

import java.util.Scanner;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;

import static spark.Spark.*;
import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;

public class App {

    public static void main(String[] args) throws Exception {
	DB db = new DB();
//	UserAdmin ua = new UserAdmin();
//	ua.select();
	ArrayList<String> users = db.getUserNames();

	port(5000);
	get("/admin", (req, res) -> {
    	Map<String, Object> model = new HashMap<>();
	model.put("users", users);
    	return new HandlebarsTemplateEngine().render(
        new ModelAndView(model, "admin.hbs")
    );
});

	get("/admin/addUser", (req, res) -> {
    	Map<String, Object> model = new HashMap<>();
	model.put("users", users);
    	return new HandlebarsTemplateEngine().render(
        new ModelAndView(model, "addUser.hbs")
    );
});

}

}
